export const projects = [
  {
    title: "Art Corner | A Responsive Image Generation Website",
    img: "/preview/preview1.png",
    description: "A minimalist image generation platform built with bootstrap and next js, focusing on a clean user experience.",
    tech: ["Next.js", "Tailwind", "MongoDB", "REST API", "Express js"],
    github: "https://github.com/Ishan1012/Art-Corner-Web-App",
    live: "https://artcornerjs.vercel.app/",
    isOngoing: false,
  },
  {
    title: "MemoMate | An Interactive Mobile App",
    img: "",
    description: "MemoMate is a cross-platform React Native app that helps users track moods and daily thoughts with a clean, emoji-powered journal interface.",
    tech: ["React Native", "Expo", "Node.js"],
    github: "https://github.com/Ishan1012/first-app",
    live: "#",
    isOngoing: false,
  },
  {
    title: "TestBuddy | A Web API Testing Web App",
    img: "/preview/preview3.png",
    description: "TestBuddy is a web-based API testing tool designed to help developers and QA engineers create, run, and manage test cases for RESTful APIs.",
    tech: ["React.js", "Bootstrap"],
    github: "https://github.com/Ishan1012/web-api-testing",
    live: "https://apitestbuddy.vercel.app/",
    isOngoing: false,
  },
  {
    title: "Wellnest | A Medical Appointment Booking Software",
    img: "",
    description: "A comprehensive medical clinic software designed to streamline patient management, appointments, and billing. Enhances clinic efficiency with user-friendly interfaces and robust data handling features.",
    tech: ["Next.js", "Tailwind", "MongoDB", "REST API", "Express js"],
    github: "https://github.com/Ishan1012/medical-software",
    live: "https://wellnestjs.vercel.app/",
    isOngoing: true,
  },
  {
    title: "Code Diary | A Collection Of Mini Projects",
    img: "/preview/preview2.png",
    description: "A collection of mini project made by using HTML, CSS and Javascript. It is a gamified portfolio of my mini projects.",
    tech: ["Next.js", "Tailwind", "REST API"],
    github: "https://github.com/Ishan1012/portfolio",
    live: "https://thecodediary.vercel.app/",
    isOngoing: true,
  },
  {
    title: "CodeDuo | A Gamified Quiz App for Coders",
    img: "/preview/preview6.png",
    description: "A coding quiz application with user authentication, leaderboards, and interactive quizzes.",
    tech: ["Next.js", "Tailwind", "MongoDB", "REST API", "Express js"],
    github: "https://github.com/Ishan1012/codeduo",
    live: "https://codeduojs.vercel.app/",
    isOngoing: true,
  },
];
